[package]
name = "aoc2017"
version = "0.1.0"
authors = ["knkski"]
edition = "2018"

[dependencies]
flame = '*'


[[bin]]
name = "day22"
path = "src/day22.rs"

[[bin]]
name = "day25"
path = "src/day25.rs"
